# Generated by Django 3.1.7 on 2021-03-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.CharField(max_length=64)),
                ('album_cover', models.CharField(max_length=64)),
                ('album_name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=64)),
            ],
        ),
    ]
