# Generated by Django 3.1.7 on 2021-03-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myspotify', '0002_song_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='added_at',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_cover',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
